# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "34621d8f0ab7701fd54a2b2e6711eb93"
name = "App-Form1"
application_url = "https://app-form-tau.vercel.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://app-form-tau.vercel.app/api/auth/callback"
]

[webhooks]
api_version = "2025-07"

[build]
automatically_update_urls_on_dev = false

[app_proxy]
url = "https://app-form-tau.vercel.app/proxy"
subpath = "form"
prefix = "apps"